apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

nameSuffix: -dev

patches:
- path: ./argocd-app-patches.yaml
  target:
    kind: Application
- path: ./argocd-repo-secret-patches.yaml
  target:
    kind: Secret

resources:
- ../../../base/gitops
