apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mvp-thymeleaf-prd

resources:
- ../../base

patches:
- path: ./deployment-patches.yaml
  target:
    kind: Deployment
- path: ./ingress-patches.yaml
  target:
    kind: Ingress

images:
- name: axccoe/mvp-thymeleaf-jdk17
  newName: tiuaxcoetmpacr.azurecr.io/axccoe/mvp-thymeleaf-jdk17-prd
  newTag: "20240903015920"

resources:
- ../../base
