name: Deploy using ssh and scp

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        options:
          - arc-runner-axccoe
          - self-hosted
          - ubuntu-latest
      environment:
        description: "Deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd

jobs:
  build:
    name: (${{ inputs.environment }}) Build using maven
    runs-on: "${{ inputs.runner }}"

    steps:
    # - name: Cache Maven packages
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.m2/repository
    #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-maven-

    # - name: Set up jdk 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    #     cache: maven
            
    - name: Check out the repo
      # uses: actions/checkout@v4.1.7
      uses: ./../../common/actions/checkout-v4.1.7
      with:
        fetch-depth: 1
        # path: ${{ github.event.repository.name }}-${{ github.ref_name }}

    - name: Configure maven settings.xml
      run: |
          cat <<EOF > ./settings.xml
          <settings>
          <servers>
              <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GH_ADMIN_TOKEN }}</password>
              </server>
          </servers>
          </settings>
          EOF

    - name: Package jar file
      run: mvn -B -DskipTests package --file ./pom.xml -s ./settings.xml

  deploy-dev:
    name: (${{ inputs.environment }}) Deploy using ssh and scp
    runs-on: "${{ inputs.runner }}"
    needs: build
    if: ${{ inputs.environment == 'dev' }}
    steps:
      - name: Deploy java app
        uses: ./.github/workflows/actions/deploy-ssh-vm
        with:
          environment: "${{ inputs.environment }}"
          ssh-private-key: "${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}"
          vm-prefix: "${{ vars.AZURE_VM_PREFIX }}"
          vm-suffix: "vm"
          vm-ip: "${{ secrets.AZURE_VM_IP_DEV }}"
          vm-user: "${{ vars.AZURE_VM_USER }}"
          app-name: "${{ vars.APP_NAME }}"

  deploy-prd:
    name: (${{ inputs.environment }}) Deploy using ssh and scp
    runs-on: "${{ inputs.runner }}"
    needs: build
    if: ${{ inputs.environment == 'prd' }}
    strategy:
      matrix:
        vm-ips: [prd1, prd2]
    steps:
      - name: Extract VM IP
        run: echo "TARGET_VM_IP=$(echo '${{ secrets.AZURE_VM_IP_PRD }}' | jq -r .${{ matrix.vm-ips }} )" >> $GITHUB_ENV

      - name: Deploy java app
        uses: ./.github/workflows/actions/deploy-ssh-vm
        env:
          TARGET_VM_IP: ${{ env.TARGET_VM_IP }}
        with:
          environment: "${{ inputs.environment }}"
          ssh-private-key: "${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}"
          vm-prefix: "${{ vars.AZURE_VM_PREFIX }}"
          vm-suffix: "vm"
          vm-ip: "${{ env.TARGET_VM_IP }}"
          vm-user: "${{ vars.AZURE_VM_USER }}"
          app-name: "${{ vars.APP_NAME }}"
