name: Publish image and update manifests

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        options:
          - arc-runner-axccoe
          - self-hosted
          - ubuntu-latest
      environment:
        description: "Deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd

jobs:
  ci:
    name: (${{ inputs.environment }}) Push Container image and Update K8s Manifests
    runs-on: "${{ inputs.runner }}"

    steps:
      - name: Check out the repo
        # uses: actions/checkout@v4.1.7
        uses: ./../../common/actions/checkout-v4.1.7
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 1
          # path: ${{ github.event.repository.name }}-${{ github.ref_name }}

      - name: Get image tag
        run: echo "IMAGE_TAG=$(TZ=Asia/Seoul date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Configure maven settings.xml
        run: |
          cat <<EOF > ./settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_ADMIN_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF


      - name: Log in to Azure CLI
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo "$AZURE_CREDENTIALS" > azure_credentials.json
          az login \
            --service-principal \
            --username $(jq -r .clientId azure_credentials.json) \
            --password $(jq -r .clientSecret azure_credentials.json) \
            --tenant $(jq -r .tenantId azure_credentials.json)
          az account set --subscription $(jq -r .subscriptionId azure_credentials.json)

      - name: Login to ACR Private
        run: |
          az acr login --name ${{ vars.ACR_NAME }}

      - name: Set up Docker Buildx
        # uses: docker/setup-buildx-action@v3.6.1
        uses: ./../../common/docker/setup-buildx-action-v3.6.1

      - name: Build and push Container image
        # uses: docker/build-push-action@v6.5.0
        uses: ./../../common/docker/build-push-action-v6.5.0
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}-cache
          cache-to: type=registry,ref=${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}-cache,mode=max
          tags: | 
            ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}-${{ inputs.environment }}:${{ env.IMAGE_TAG }}
            ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}-${{ inputs.environment }}:latest

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0
        # uses: ./../../common/Azure/setup-kubectl-v4.0.0
        with:
          version: latest

      - name: Update kubernetes manifest
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          cd manifests/overlays/${{ inputs.environment }}
          kustomize edit set image ${{ vars.ACR_REPOSITORY }}=${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}-${{ inputs.environment }}:${{ env.IMAGE_TAG }}

          git config --global user.name 'github-actions[bot]'
          git config --global user.email '<>'  
          git add .
          git commit -m 'k8s manifest for image tag: ${{ env.IMAGE_TAG }}'
          git push origin main -f
